[project]
name = "uv-docker-demo"
version = "0.1.0"
description = "uv docker demo for codemageddon.me blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
]
